### ISSUE TITLE
Add support for vuepress 2.x

### ISSUE THREAD

**Issue by B4night** [mark-magic/mark-magic#6]

**Comment by rxliuli** [comment]
Can use [@mark-magic/plugin-local](https://mark-magic.rxliuli.com/plugin/plugin-local.html) directly? For example

1. `npm i @mark-magic/cli @mark-magic/plugin-local @mark-magic/plugin-joplin`
2. add config file `mark-magic.config.yaml`
```yaml
tasks:
  - name: blog
    input:
      name: '@mark-magic/plugin-joplin'
      config:
        baseUrl: 'http://localhost:41184'
        token: '***' # joplin web clipper service token
        tag: blog # filter notes by tag
    output:
      name: '@mark-magic/plugin-local'
      config:
        path: './src/posts'
```
3. `pnpm mark-magic`

**Comment by B4night** [comment]
Yes, I figured out the same solution and when I tried to add comments, I saw your answer lol.
I know little about the frontend, so that's almost the simplest way I can figure out.
Anyway, thanks for your kind help.

**Comment by rxliuli** [comment]
Thank you for the reminder 🙏. I just noticed some minor issues with plugin-joplin, and I have just fixed and released @mark-magic/plugin-joplin@0.11.7.

**Comment by B4night** [comment]
Update: I tried  `plugin-joplin` as input and `plugin-local` as output and I found that the frontmatter information was not generated. Then I used `plugin-hexo` and shell script to fix this.
``` yaml
tasks:
  - name: blog
    input:
      name: '@mark-magic/plugin-joplin'
      config:
        baseUrl: 'http://localhost:41184'
        token:  xxxx  # joplin web clipper service token
        tag: tutorial # filter notes by tag
    output:
      name: '@mark-magic/plugin-hexo' # Output plugin to generate the files required by Hexo
      config:
        path: './hexo' # The root directory of the Hexo project
```

After executing `npx mark-magic`, all the md file tagged with `tutorial` would be stored at the `./hexo/` directory. I use a script to automatically execute this. I removed some useless information in the frontmatter and generated some.

``` sh
#!/bin/bash
mkdir hexo
npx mark-magic

hexo_dir="./hexo/source/_posts"
pushd $hexo_dir
for md_file in *.md; do
    file_name=$(cat $md_file | grep "title: " | awk -F ": " '{print $2}')
    timestamp_ms=$(cat $md_file | grep "date: " | awk -F ": " '{print $2}')
    timestamp_sec=$(($timestamp_ms / 1000))
    file_date=$(date -d "@$timestamp_sec" '+%Y-%m-%d')
    sed -i '/tags:/d; /updated:/d; /date:/d; /abbrlink:/d; /layout:/d' $md_file
    sed -i "2i date: $file_date" $md_file
    sed -i "2i author: B4night" $md_file
    # sed -i "4d" $md_file
    # mv $md_file "${file_name}".md
    mv $md_file ../../../src/posts/"${file_name}".md
    # pwd
done

popd
rm -rf hexo

npm run docs:build
git add .
today=$(date '+%Y-%m-%d')
git commit -s -m "update ${today}"
git push
```
